cifir/urls.py
from re import template
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import PasswordChangeDoneView, PasswordChangeView
from django.urls import reverse_lazy


# #API
# from django.urls import re_path
# from rest_framework.authtoken.views import obtain_auth_token
# from .views import CreateUserAPIView, LogoutUserAPIView

# from django.urls import path

from .views import *

#paths arranged alphabetically by name
app_name = 'cifir'
urlpatterns = [ 
    # path('api/data', views.get_data, name='api-data'),

    #TURL
    path('index/', views.loginPageView.as_view(), name="login_view"),
    path('logout/', views.logoutPage, name='logout_view'),
    path('admin/', views.adminPageView.as_view(), name='admin_view'),
    path('home/', views.homePageView.as_view(), name='home_view'),
    path('collections/', views.collectionsPageView.as_view(), name="collections_view"),
    path('networklibraries/', views.networkLibrariesPageView.as_view(), name="networklibraries_view"),
    path('books/', views.viewBook.as_view(), name="book_view"),
    #path('books/', views.book, name="files_view"),
    path('favorites/', views.favoritesPageView.as_view(), name="favorites_view"),
    path('toread/', views.toReadPageView.as_view(), name="toread_view"),
    path('haveread/', views.haveReadPageView.as_view(), name="haveread_view"),
    path('epub/', views.epubReadpageView.as_view(), name="epub_view"),
    path('pdf/', views.pdfReadpageView.as_view(), name="pdf_view"),
    path('profile/', views.profilePageView.as_view(), name="profile_view"),
    path('password/', 
        auth_views.PasswordChangeView.as_view(template_name = 'changePassword.html', 
        success_url = reverse_lazy('cifir:login_view')),name="changePassword_view"),

    # url(r'^auth/login/$',
    #     obtain_auth_token,
    #     name='auth_user_login'),
    # url(r'^auth/register/$',
    #     CreateUserAPIView.as_view(),
    #     name='auth_user_create'),
    # url(r'^auth/logout/$',
    #     LogoutUserAPIView.as_view(),
    #     name='auth_user_logout'),
    # path('book/',
    #      views.BookList.as_view(),
    #      name='booklist'),
    # path('bookdetails/<int:id>/',
    #      views.BookDetails.as_view(),
    #      name='bookdetails'),
    # path('collection/',
    #      views.CollectionList.as_view(),
    #      name='collectionlist'),
    # path('collectiondetails/<int:id>/',
    #      views.CollectionDetails.as_view(),
    #      name='collectiondetails'),


    
               
]
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cifirproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cifir/', include('cifir.urls', namespace='cifir'))

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cifir/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.auth.admin import UserAdmin
from django import forms

# Create your models here.

class Book(models.Model):
	title = models.CharField(max_length=250)
	book_author = models.CharField(max_length=250)
	cover = models.ImageField(upload_to='media')
	file = models.FileField(upload_to='media')
	user = models.ManyToManyField(User, blank=True)
	isFavorite = models.BooleanField(default=False)
	isHaveRead = models.BooleanField(default=False)
	isToRead = models.BooleanField(default=False)
	isAddedToCol = models.BooleanField(default=False)
	isDeleted = models.BooleanField(default=False)

	class Meta:
		db_table = "Book"
		verbose_name_plural = "Books"

	def __str__(self):
		return self.title

class Collection(models.Model):
	name = models.CharField(max_length=250)
	book = models.ManyToManyField(Book, blank=True)
	user = models.ManyToManyField(User, blank=True)
	isDeleted = models.BooleanField(default=False)

	class Meta:
		db_table = "Collection"
		verbose_name_plural = "Collections"

	def __str__(self):
		return self.name

class Note(models.Model):
	book = models.ForeignKey(Book, on_delete=models.CASCADE, null=True, blank=True, related_name="notes_book")
	title = models.CharField(max_length=250)
	content = models.CharField(max_length=250)

	class Meta:
		db_table = "Note"
		verbose_name_plural = "Notes"

	def __str__(self):
		return self.title

class Catalog(models.Model):
	name = models.CharField(max_length=250)
	link = models.CharField(max_length=250)
	description = models.CharField(max_length=250)
	cover = models.CharField(max_length=250)
	defaultUsername = models.CharField(max_length=150)
	defaultPassword = models.CharField(max_length=100)
	count = models.IntegerField()

	class Meta:
		db_table = "Catalog"
		verbose_name_plural = "Catalogs"

	def __str__(self):
		return self.name

class Bookmark(models.Model):
	bookpage = models.CharField(max_length=250)
	book = models.ManyToManyField(Book, blank=True)
	page_index = models.CharField(max_length=250)
	
	is_removed = models.BooleanField(default=False)	

	class Meta:
		db_table = "Bookmark"
		verbose_name_plural = "Bookmarks"

	def __str__(self):
		bookTitle = self.book.all().first()
		return bookTitle.title

# class AuthUser(models.Model):
#     password = models.CharField(max_length=128)
#     last_login = models.DateTimeField(blank=True, null=True)
#     is_superuser = models.IntegerField()
#     username = models.CharField(unique=True, max_length=150)
#     first_name = models.CharField(max_length=150)
#     last_name = models.CharField(max_length=150)
#     email = models.CharField(max_length=254)
#     is_staff = models.IntegerField()
#     is_active = models.IntegerField()
#     date_joined = models.DateTimeField()

#     class Meta:
#         managed = False
#         db_table = 'auth_user'

cifir/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth.models import User
from django import forms
from cifir.models import Book


class CreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['first_name','last_name','username', 'email', 'password1', 'password2']

class BookForm(forms.ModelForm):
	class Meta:
 		model = Book
 		fields = ['file']

class PasswordChangingForm(PasswordChangeForm):
	old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'type':'password'}))
	new_password1 = forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={'class': 'form-control', 'type':'password'}))
	new_password2 = forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={'class': 'form-control', 'type':'password'}))
	class Meta:
 		model = User
 		fields = ['old_password','new_password1','new_password2']

cifir/views.py
import django
django.setup()
from re import template
from .forms import *
from .models import *
from .forms import CreateUserForm, PasswordChangingForm
from itertools import chain
from django.views.generic import View
from django.urls import reverse_lazy
from django.conf import settings
from django.shortcuts import render,redirect
from django.http import HttpResponse, Http404
from django.contrib.auth.forms import PasswordChangeForm, UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User, auth
from django.contrib import messages, admin
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.backends import ModelBackend
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.db.models import Q 

#tts
import pyttsx3
import multiprocessing as mp
import urllib3
import io
#pdf
import pdfplumber
import keyboard

#epub
from ebooklib import epub
import ebooklib
from bs4 import BeautifulSoup

#epub metadata, book cover etc
from lxml import etree
import zipfile
from PIL import Image
from io import BytesIO
from django.core.files.base import ContentFile

#automate login
from selenium import webdriver 
from selenium.webdriver.common.keys import Keys 
from selenium.webdriver.chrome.options import Options 
import time
import undetected_chromedriver as chromedriver
import csv, sys, os, django, random
from datetime import datetime
from pathlib import Path
import os

from splinter import Browser

from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

#API
# import collections
# from django.contrib import auth
# from django.contrib.auth import get_user_model
# from rest_framework.generics import CreateAPIView
# from rest_framework.permissions import AllowAny
# from rest_framework.response import Response
# from rest_framework.authtoken.models import Token
# from rest_framework import status
# from rest_framework.serializers import Serializer
# from rest_framework.views import APIView

# from rest_framework.decorators import APIView

# from cifir.serializers import CollectionSerializer, CreateUserSerializer, UserSerializer
# from cifir.serializers import BookSerializer

def setDriverOptions():
	# options = chromedriver.ChromeOptions()
	# options = webdriver.ChromeOptions()
	options = Options()
	# options.add_experimental_option("detach", True)
	options.binary_location = os.environ.get("GOOGLE_CHROME_BIN")
	
	print(os.environ.get("GOOGLE_CHROME_BIN"))

	options.add_argument("--no-sandbox")
	options.add_argument('--disable-dev-shm-usage')
	options.set_capability("detach", True)

	return options

#selenium
def automateLogin(request, username, password, url, loginBtnSelector, indicator):
	driver = chromedriver.Chrome(executable_path=os.environ.get("CHROMEDRIVER_PATH"), options=setDriverOptions())
	# driver = webdriver.Chrome(executable_path=os.environ.get("CHROMEDRIVER_PATH"), options=setDriverOptions())
	if indicator == 1:
		driver.get(url)

		print('fffff')
		
		username_field = driver.find_element_by_css_selector("#username")
		username_field.send_keys(username)
		driver.execute_script("document.querySelector('#password').setAttribute('value','"+ password +"')")
		driver.execute_script("document.querySelector('"+ loginBtnSelector +"').click();")

# Create your views here.
def updateBookStatus(item, book_id):
	# revise code to add and remove from favorite, ishaveread, and istoread
	books = Book.objects.filter(id=book_id)
	if (item == "favorite"):
		isFavorite = not books[0].isFavorite
		Book.objects.filter(id=book_id).update(isFavorite=isFavorite)
	elif (item == 'have-read'):
		isHaveRead = not books[0].isHaveRead
		Book.objects.filter(id=book_id).update(isHaveRead=isHaveRead)
	elif (item == 'to-read'):
		isToRead = not books[0].isToRead
		Book.objects.filter(id=book_id).update(isToRead=isToRead)

def addToCollection(book_id, collection_id):
	print("book id: ", book_id)
	print("collection id: ", collection_id)
	book = Book.objects.get(id=book_id)
	collection = Collection.objects.get(id=collection_id)
	collection.book.add(book)
	print('book added')

def automateLoginToSite(request, username, password, url, loginBtnSelector, indicator):
	global browser
	browser = Browser('chrome')
	if indicator == 1:
		try:
			browser.visit(url)
			browser.find_by_css("#username").fill(username)
			browser.find_by_css("#password").fill(password)
			browser.find_by_css(loginBtnSelector).click()
		except:
			messages.success(request,'Failed to access the database. Try Again Later.')
	if indicator == 2:
		try:
			browser.visit(url)
		except:
			messages.success(request,'Failed to access the database. Try Again Later.')


def epubtotext(bookFile):
	bookFile = bookFile

	url = "https://cifirstorage.blob.core.windows.net/media/" + bookFile
	print(url)

	http = urllib3.PoolManager()
	temp = io.BytesIO()
	temp.write(http.request("GET", url).data)
	print(temp)

	book = epub.read_epub(temp)

	for item in book.get_items():
		if item.get_type() == ebooklib.ITEM_DOCUMENT:
			soup = BeautifulSoup(item.get_body_content(), 'html.parser')
			text = [para.get_text() for para in soup.find_all('p')]
			txt = soup.text.replace('\n', '' '').strip()
			tts(txt)
	
def pdftotext(bookFile,currentPage):

	bookFile = bookFile
	currentPage = int(currentPage)
	print(bookFile)
	print('tts activated')
	print(currentPage)

	url = "https://cifirstorage.blob.core.windows.net/media/" + bookFile
	print(url)

	http = urllib3.PoolManager()
	temp = io.BytesIO()
	temp.write(http.request("GET", url).data)
	print(temp)

	with pdfplumber.open(temp) as pdf:
		text = pdf.pages[currentPage].extract_text()
		tts(text)

	# pdf = pdfplumber.open(path)

	# #1 page only
	# page = pdf.pages[currentPage]
	# text = page.extract_text()
	# tts(text)

	# start from currentpage until sa mga next
	# totalpages = len(pdf.pages)
	# for i in range(currentPage, totalpages ):
	#     page = pdf.pages[i]
	#     page_content = page.extract_text()
	# tts(page_content)


def tts(text):
	
	p = mp.Process(target=speak, args=(text,))
	p.start()
	while p.is_alive():
		if keyboard.is_pressed('spacebar'):
			p.terminate()
		else:
			continue
	p.join()

def speak(text):
	speak = pyttsx3.init('sapi5')
	voices = speak.getProperty('voices')
	speak.setProperty("rate", 178)
	speak.setProperty("voice", voices[0].id)
	speak.say(text)
	speak.runAndWait()


#CLASSES
class homePageView(View):
	def get(self, request):
		user = User.objects.filter(username=request.user)
		collection = Collection.objects.filter(user=request.user).filter(isDeleted=False)
		catalogs = Catalog.objects.all()
		book = Book.objects.filter(user=request.user)

		context = {
				'collections' : collection,
				'catalog' : catalogs,
				'users' : user,
				'books' : book,
				}

		return render(request, 'homepage.html', context)

	def post(self,request):
		if request.method == "POST":
			#NETWORK LIBRARIES
			username = request.POST.get("username")
			password = request.POST.get("password")
			url = request.POST.get("link")

			#convert webElement to string
			uname = str(username)
			pword = str(password)

			if "Cambridge Core" in request.POST:
				loginBtnSelector = '#login-form > div:nth-child(5) > button'
				# automateLoginToSite(request, username, password, url, loginBtnSelector, 1)
				automateLogin(request, username, password, url, loginBtnSelector, 1)
				return redirect('cifir:home_view')

			elif "ProQuest Elibrary" in request.POST:
				loginBtnSelector = '#login_button'
				automateLoginToSite(request, username, password, url, loginBtnSelector, 1)
				return redirect('cifir:home_view')

			elif "Wiley Online Library" in request.POST:
				loginBtnSelector = '#main-content > div > div > div.container > div > div > div.card.card--light-shadow.login-widget.col-md-6 > div.widget__body > div.login-form > form > div.align-end > span > input'
				automateLoginToSite(request, username, password, url, loginBtnSelector, 1)
				return redirect('cifir:home_view')

			elif "Science Direct" in request.POST:
				global browser
				browser = Browser('chrome')
				try:
					browser.visit(url)
					browser.find_by_css("#bdd-email").fill(username)
					browser.find_by_css('#bdd-elsPrimaryBtn').click()
					browser.find_by_css("#bdd-password").fill(password)
					browser.find_by_css('#bdd-elsPrimaryBtn').click()
				except:
					messages.success(request,'Failed to access the database. Try Again Later.')

				return redirect('cifir:home_view')

			elif "Directory of Open Access Books" in request.POST:
				automateLoginToSite(request, username, password, url, '', 2)
				return redirect('cifir:home_view')

			elif "Zlibrary" in request.POST:
				automateLoginToSite(request, username, password, url, '', 2)
				return redirect('cifir:home_view')
			
			#UPLOAD BOOK
			if 'btnUpload' in request.POST:
				user = User.objects.get(id=request.user.id)
				file = request.FILES.get('book_file')
				ext = os.path.splitext(file.name)[1]  # [0] returns path+filename
				epub_extensions = ['.epub']
				pdf_extensions = ['.pdf']

				#EPUB FILE FORMAT
				if ext.lower() in epub_extensions: 
					print(file)
					print('')
		
					namespaces = {
					   "calibre":"http://calibre.kovidgoyal.net/2009/metadata",
					   "dc":"http://purl.org/dc/elements/1.1/",
					   "dcterms":"http://purl.org/dc/terms/",
					   "opf":"http://www.idpf.org/2007/opf",
					   "u":"urn:oasis:names:tc:opendocument:xmlns:container",
					   "xsi":"http://www.w3.org/2001/XMLSchema-instance",
					   'pkg':'http://www.idpf.org/2007/opf',
					}

					zip = zipfile.ZipFile(file)
					t = etree.fromstring(zip.read("META-INF/container.xml"))

					for i in t:
						print(i)
					print('')

cifir/templates/components/NavBar.html
{% load static %}
{% if user.is_authenticated %}
<!--TOPLEFT NAVBAR-->
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="justify-content: space-between;">
  <div id="navbarNavTopLeft">
    <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="logolink" href="#">
              <img src="{% static 'images/CIFIR_Logo.png' %}" id="divLogo" height="90px" width="90px">
          </a>
        </li>
      </ul>
    </div>
<!--TOPRIGHT NAVBAR-->
    <div class="navbar-text" id="navbarNavRight">
    <ul class="navbar-nav">
       


        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="profile-dropdown">
              <i class="fas fa-user mr-2"></i>
                <div class="username">{{ user.username }}</div>
            </span>
            
          </a>

          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <form action="">
              <a class="dropdown-item" href='{% url "cifir:profile_view" %}'>Account Setting</a>
              <a class="dropdown-item" href='{% url "cifir:logout_view" %}'>Logout</a>
            </form>
          </div>
        </li>


      </ul>

    </ul>
  </div>
</nav>

<nav class="navbar navbar-expand-sm navbar-dark bg-dark menu-bar">

<!--LOW LEFT NAVBAR-->
  <div id="navbarLowNavLeft">
    <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="navbar" href='{% url "cifir:home_view" %}' data-toggle="tooltip" title="Books"> 
            <span><i class="fas fa-swatchbook"></i></span>
          </a>
          
        </li>
        <li class="nav-item active">
          <a class="navbar" href='{% url "cifir:collections_view" %}' data-toggle="tooltip" title="Collections">
            <span style="color:#FFFFFF;"><i class="far fa-folder"></i></span>
          </a>
          
        </li>
        
        <li class="nav-item active">
          <a class="navbar" href='{% url "cifir:networklibraries_view" %}'>
            <span style="color:#FFFFFF;"><i class="fas fa-globe"></i></span>
          </a>
        </li>
    </ul>
  </div>

  <!--LOW RIGHT NAVBAR-->
  <div class="navbar-text" id="navbarNavLowRight">
    <ul class="navbar-nav">
        <li class="nav-item">
          <a class="navbar" href='{% url "cifir:favorites_view" %}' data-toggle="tooltip" title="Favorites">
            <span><i class="far fa-star"></i></span>
          </a>
          
        </li>
        <li class="nav-item">
          <a class="navbar" href='{% url "cifir:toread_view" %}' data-toggle="tooltip" title="To Read">
            <span><i class="far fa-clock"></i></span>
          </a>
          
        </li>
        <li class="nav-item nav-item-last">
          <a class="navbar" href='{% url "cifir:haveread_view" %}' data-toggle="tooltip" title="Have Read">
            <span><i class="fas fa-check-double"></i></i></span>
          </a>
          
        </li>
    
    </ul>
  </div>
</nav>
</div>
{% endif %}

cifir/templates/components/NetworkLibrariesCarousel.html
{% load static %}
{% for cat in catalog %}
  <li>
    <div class="card" style="width: 18rem;">
      <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="embed-responsive embed-responsive-4by3">
          {% if cat.cover %}
            <img alt="Card image cap" class="card-img-top embed-responsive-item" src="{{ cat.cover }}" style="height: 190px; padding: 10px;" />
          {% endif %}
        </div>
        <div class="card-body">
          <h4 class="card-title">{{ cat.name }}</h4>
          <div class="card-text">
              {{ cat.description }}
        
          </div>  
          <input type="hidden" name="link" id="link" value="{{ cat.link }}">
          <input type="hidden" name="username" id="username" value="{{ cat.defaultUsername }}">
          <input type="hidden" name="password" id="password" value="{{ cat.defaultPassword }}">
          <div class="card-read-more" style="overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">
            <div class = 'countBtn'>
              <!-- <button id="{{ cat.name }}" name="{{ cat.name }}" class="btn btn-close-all">Go to {{ cat.name }}</button> -->
              <button type="submit" id="{{ cat.name }}" name="{{ cat.name }}" class="btn btn-all" style="width: 250px;">Go to {{ cat.name }}</button>
            </div>
            <div class = 'countNum' hidden>
              <h4> 0 </h4>
            </div>
            <script type="text/javascript" src="{% static 'javascript/counter.js' %}"></script>
          </div>
        </div>
      </form>
    </div>
  </li>
{% endfor %}

cifir/templates/components/TheBook.html
<div class="btn book-btn" name="book_id" value="{{book.id}}">
  <div class="dropdown">
    <a class="btn" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
      aria-expanded="false" style="padding-left: 1em;">
      <i class="fas fa-ellipsis-v" ></i>
    </a>

    <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
      
      <li>
        <a class="dropdown-item" data-toggle="modal" data-target="#addBookCollectionModal" onclick="chooseBook('{{book.id}}')">Add to Collections</a>
      </li>
      
      <!-- show this if the book is already added to collection -->
      <!-- <li>
        <a class="dropdown-item" data-toggle="modal" data-target="#addBookCollectionModal" onclick="chooseBook('{{book.id}}')">Remove from Collections</a>
      </li> -->
      
      <li>
        <a class="dropdown-item" onclick="updateBook('{{ request.path }}' ,'favorite', '{{book.id}}')">
          {% if not book.isFavorite %}
            Add to Favorites
          {% else %}
            Remove from Favorites
          {% endif %}
        </a>
      </li>
      
      <li>
        <a class="dropdown-item" onclick="updateBook('{{ request.path }}' ,'to-read', '{{book.id}}')">
          {% if not book.isToRead %}
            Add to To Read Books
          {% else %}
            Remove from To Read Books
          {% endif %}
        </a>
      </li>
      <li>
        <a class="dropdown-item" onclick="updateBook('{{ request.path }}' ,'have-read', '{{book.id}}')">
          {% if not book.isHaveRead %}
            Add to Have Read Books
          {% else %}
            Remove from Have Read Books
          {% endif %}
        </a>
      </li>
    </ul>
  </div>
  
    <div onclick="openBook('{{book.id}}', '{{book.file.url}}')">
      <div class="i-folders">
          {% if book.cover %}
            <img src="{{book.cover.url}}"alt ="{{book.title}}"
            style ="height: 160px; width:110px" >
      
          {% endif %}
      </div>
      <div class="book-title">
        <h6>{{ book.title}}</h6>
      </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="addBookCollectionModal" tabindex="-1" role="dialog" aria-labelledby="addCollectionModal"
  aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Choose collection</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body collection-folders">
        {% for collection in collections %}
          {% csrf_token %}
          <button class="btn book-btn" name="collection" value="{{collection.name}}"
            data-toggle="tooltip" title="{{collection.name}}" onclick="addToCollection('{{collection.id}}')">
            <div class="i-folders">
              <i class="fas fa-folder"></i>
            </div>

            {{collection.name}}
          </button>
        {% endfor %}
      </div>
      </form>
    </div>
  </div>
</div>

{% block extrascriptfooter %}
<script>
  // source: https://stackoverflow.com/questions/133925/javascript-post-request-like-a-form-submit
  var book_id;
  function chooseBook(id){
    book_id = id
  }
  function addToCollection(collection_id) {
    console.log("book: ", book_id)
    console.log("collection_id: ", collection_id)
    post('{% url "cifir:home_view" %}', {
      book_id,
      collection_id,
      csrfmiddlewaretoken: "{{csrf_token}}",
      addToCollection: "",
    });
  }

  function removeFromCollection(book_id) {
    console.log("book: ", book_id)
    post('{% url "cifir:home_view" %}',  {
      book_id,
      csrfmiddlewaretoken: "{{csrf_token}}",
      removeFromCollection: "",
    });
  }

  function openBook(book_id, book_file) {
    extension = book_file.split('.').pop();
    console.log(extension)
    if(extension == "epub") {
      post('{% url "cifir:epub_view" %}', {
      book_id,
      book_file,
      csrfmiddlewaretoken: "{{csrf_token}}",
    });
    }
    else
      post('{% url "cifir:pdf_view" %}', {
      book_id,
      book_file,
      csrfmiddlewaretoken: "{{csrf_token}}",
    });
    
  }

  function updateBook(currentURL, item, book_id) {
    if (item === "favorite") {
      post(currentURL, {
        book_id,
        item: "favorite",
        csrfmiddlewaretoken: "{{csrf_token}}",
        updateBookStatus: "",
      });
    }
    if (item === "to-read") {
      post(currentURL, {
        book_id,
        item: "to-read",
        csrfmiddlewaretoken: "{{csrf_token}}",
        updateBookStatus: "",
      });
    }
    if (item === "have-read") {
      post(currentURL,  {
        book_id,
        item: "have-read",
        csrfmiddlewaretoken: "{{csrf_token}}",
        updateBookStatus: "",
      });
    }
  }

  function post(path, params, method = "post") {
    const form = document.createElement("form");
    form.method = method;
    form.action = path;

    for (const key in params) {
      if (params.hasOwnProperty(key)) {
        const hiddenField = document.createElement("input");
        hiddenField.type = "hidden";
        hiddenField.name = key;
        hiddenField.value = params[key];

        form.appendChild(hiddenField);
      }
    }
    document.body.appendChild(form);
    form.submit();
  }
</script>

{% endblock extrascriptfooter %}

cifir/templates/components/TheFolder.html
<button
  type="submit"
  class="btn book-btn"
  name="collection"
  value="{{collection.name}}"
  form="collectionform"
  data-toggle="tooltip"
  title="{{collection.name}}"
>
  <div class="i-folders">
    <i class="fas fa-folder"></i>
  </div>
{{collection.name}}
</button>

cifir/templates/components/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert {{ message.tags }} m-2" id="msg" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %} 


<script defer>
	$(document).ready(function() {
    // show the alert
    setTimeout(function() {
        $(".alert").alert('close');
    }, 2000);
});
</script>